<?php
// GENERATED by tools/build-previews.py from templates/php/index.php - edit that file.
// Social Widget - Simple HTML starter: the one server file (PHP 8).
// index.html fetches this file; it calls Taggbox and returns JSON. The token stays
// on this server; the browser only ever receives HTML.
//
// Settings (.env or the host's environment): ACCESS_TOKEN, API_BASE_URL, WIDGET_THEME.
// Look: themes/<WIDGET_THEME>.css, plus custom.css (optional) for your own changes.

declare(strict_types=1);

const CACHE_TTL_SECONDS = 300; // 5 minutes: about 288 API calls a day, whatever the traffic

// ---------- settings ----------

/** getenv() first (cPanel, Docker...), else a tiny .env reader - no Composer needed. */
function sw_env(string $key, string $default = ''): string
{
    $value = getenv($key);
    if ($value !== false && $value !== '') {
        return $value;
    }
    static $file = null;
    if ($file === null) {
        $file = [];
        $path = __DIR__ . '/.env';
        if (is_readable($path)) {
            foreach (file($path, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES) as $line) {
                $line = trim($line);
                if ($line === '' || $line[0] === '#' || !str_contains($line, '=')) {
                    continue;
                }
                [$k, $v] = array_map('trim', explode('=', $line, 2));
                $file[$k] = trim($v, "\"'");
            }
        }
    }
    return $file[$key] ?? $default;
}

// ---------- theme ----------

function sw_theme(): array
{
    $slug = strtolower(trim(sw_env('WIDGET_THEME', 'modern-card')));
    if (!preg_match('/^[a-z-]+$/', $slug) || !is_file(__DIR__ . "/themes/$slug.json")) {
        error_log("[social-widget] Unknown WIDGET_THEME \"$slug\" - using modern-card");
        $slug = 'modern-card';
    }
    $meta = json_decode((string) file_get_contents(__DIR__ . "/themes/$slug.json"), true);
    $css = (string) file_get_contents(__DIR__ . "/themes/$slug.css");
    if (is_file(__DIR__ . '/custom.css')) {
        $css .= "\n  /* custom.css */\n" . file_get_contents(__DIR__ . '/custom.css');
    }
    return ['meta' => $meta, 'css' => $css];
}

function sw_samples(array $theme): array
{
    $file = ($theme['meta']['type'] ?? '') === 'review' ? 'reviews.json' : 'social.json';
    return json_decode((string) file_get_contents(__DIR__ . "/samples/$file"), true) ?: [];
}

// ---------- API + cache ----------

function sw_fetch_posts(string $base, string $token): array
{
    $url = "$base/v3/posts?limit=24";
    $headers = ["Authorization: Bearer $token", 'Accept: application/json'];
    if (function_exists('curl_init')) {
        $ch = curl_init($url);
        curl_setopt_array($ch, [CURLOPT_RETURNTRANSFER => true, CURLOPT_HTTPHEADER => $headers, CURLOPT_TIMEOUT => 10]);
        $raw = curl_exec($ch);
        $code = (int) curl_getinfo($ch, CURLINFO_HTTP_CODE);
        if ($raw === false) {
            throw new RuntimeException('Taggbox API request failed: ' . curl_error($ch));
        }
    } else {
        $ctx = stream_context_create(['http' => ['header' => implode("\r\n", $headers), 'timeout' => 10, 'ignore_errors' => true]]);
        $raw = @file_get_contents($url, false, $ctx);
        if ($raw === false) {
            throw new RuntimeException('Taggbox API request failed');
        }
        $code = preg_match('/\s(\d{3})/', $http_response_header[0] ?? '', $m) ? (int) $m[1] : 0;
    }
    $json = json_decode((string) $raw, true);
    // Check the HTTP status AND the envelope flag: status can be false on a 200.
    if ($code < 200 || $code >= 300 || !is_array($json) || ($json['status'] ?? true) === false) {
        $detail = $code === 422 ? json_encode($json['body']['fields'] ?? null) : ($json['message'] ?? 'unexpected response');
        throw new RuntimeException("Taggbox API $code: $detail");
    }
    $body = is_array($json['body'] ?? null) ? $json['body'] : [];
    return ['posts' => is_array($body['posts'] ?? null) ? $body['posts'] : [], 'paging' => $body['paging'] ?? null];
}

function sw_read_cache(string $file): ?array
{
    $c = is_readable($file) ? json_decode((string) @file_get_contents($file), true) : null;
    return is_array($c) && isset($c['data']) ? $c : null;
}

function sw_get_posts(array $theme): array
{
    $token = trim(sw_env('ACCESS_TOKEN'));
    // No token yet: show the sample posts, touch neither the API nor the cache.
    if ($token === '') {
        return ['posts' => sw_samples($theme), 'paging' => null, 'sample' => true];
    }
    $base = rtrim(trim(sw_env('API_BASE_URL', 'https://api.taggbox.com/api')), '/');
    $dir = __DIR__ . '/cache';
    $file = "$dir/posts.json";

    $cached = sw_read_cache($file);
    if ($cached && time() - (int) $cached['saved_at'] < CACHE_TTL_SECONDS) {
        return $cached['data'];
    }

    // One refresh at a time: whoever gets the lock refreshes, the rest serve the old copy.
    if (!is_dir($dir)) {
        @mkdir($dir, 0775, true);
    }
    $lock = @fopen("$dir/posts.lock", 'c');
    if ($lock && !flock($lock, LOCK_EX | LOCK_NB)) {
        if ($cached) {
            fclose($lock);
            return $cached['data'];
        }
        flock($lock, LOCK_EX); // nothing to serve yet - wait for the other refresh
        $fresh = sw_read_cache($file);
        if ($fresh && time() - (int) $fresh['saved_at'] < CACHE_TTL_SECONDS) {
            fclose($lock);
            return $fresh['data'];
        }
    }

    try {
        $data = sw_fetch_posts($base, $token);
        // Write a temp file and rename it in, so a reader never sees half a file.
        $tmp = "$file." . getmypid() . '.tmp';
        if (@file_put_contents($tmp, json_encode(['saved_at' => time(), 'data' => $data])) === false || !@rename($tmp, $file)) {
            @unlink($tmp);
            error_log('[social-widget] Cache folder not writable, serving live');
        }
    } catch (Throwable $e) {
        error_log('[social-widget] ' . $e->getMessage());
        // A failed refresh keeps serving the old copy; empty only if nothing ever loaded.
        $data = $cached ? $cached['data'] : ['posts' => [], 'paging' => null];
    }
    if ($lock) {
        fclose($lock);
    }
    return $data;
}

// ---------- JSON for index.html ----------
// posts.php        -> { posts, paging, sample, theme }  (theme = how to lay out a card)
// posts.php?css=1  -> the theme CSS (and custom.css), with its Google Font

$theme = sw_theme();
if (isset($_GET['css'])) {
    header('Content-Type: text/css; charset=utf-8');
    $font = $theme['meta']['font_url'] ?? '';
    echo ($font ? '@import url("' . $font . "\");\n" : '') . $theme['css'];
    exit;
}
try {
    $data = sw_get_posts($theme);
} catch (Throwable $e) {
    error_log('[social-widget] ' . $e->getMessage());
    $data = ['posts' => [], 'paging' => null];
}
header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-store');
echo json_encode([
    'posts' => $data['posts'] ?? [],
    'paging' => $data['paging'] ?? null,
    'sample' => !empty($data['sample']),
    'theme' => $theme['meta'],
], JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
